feat: Return location for message attachments
Satellite-im/Warp pull request #480
Opened 2024-03-20 14:04 UTC by Flemmli97

**What this PR does** 📖

Makes it so the original location is also returned when sending a message with attachments to it. 
The returned stream is now a pair of (optional) Location + Progress

2024-03-20 17:21 UTC, dariusc93 requested changes
If we are to use `Location`, maybe we should push that into `AttachmentKind::AttachedProgress` instead? That way we dont need to change the stream output itself but only `AttachmentKind`

2024-03-20 17:21 UTC, dariusc93 commented on extensions/warp-ipfs/src/store/message.rs
> +                match file.clone() {
You can borrow this instead

```suggestion
                match &file {
```

2024-03-21 12:42 UTC, Flemmli97 commented
> If we are to use `Location`, maybe we should push that into `AttachmentKind::AttachedProgress` instead? That way we dont need to change the stream output itself but only `AttachmentKind`



> If we are to use `Location`, maybe we should push that into `AttachmentKind::AttachedProgress` instead? That way we dont need to change the stream output itself but only `AttachmentKind`

idk why i thought that was used somewhere else which is why i initially didn't do it.
changed it now

2024-03-21 19:42 UTC, dariusc93 approved these changes

2024-03-21 19:42 UTC, merged